{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0427d40c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 / 1000\n"
     ]
    },
    {
     "ename": "ExceptionGroup",
     "evalue": "12 exceptions were raised in the task group:\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mExceptionGroup\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 107\u001b[0m\n\u001b[1;32m    105\u001b[0m \u001b[39mfor\u001b[39;00m task \u001b[39min\u001b[39;00m benchmark_files:\n\u001b[1;32m    106\u001b[0m     model \u001b[39m=\u001b[39m RecipeModel(agent_name\u001b[39m=\u001b[39magent)\n\u001b[0;32m--> 107\u001b[0m     accuracy, answers \u001b[39m=\u001b[39m \u001b[39mawait\u001b[39;00m evaluate_task(task, model, agent, \u001b[39m1000\u001b[39m, amplification\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m)\n\u001b[1;32m    108\u001b[0m     accuracy, answers \u001b[39m=\u001b[39m \u001b[39mawait\u001b[39;00m evaluate_task(task, model, agent, \u001b[39m1000\u001b[39m, amplification\u001b[39m=\u001b[39m\u001b[39mFalse\u001b[39;00m)\n",
      "Cell \u001b[0;32mIn[1], line 57\u001b[0m, in \u001b[0;36mevaluate_task\u001b[0;34m(task_name, model, agent_name, task_count, amplification)\u001b[0m\n\u001b[1;32m     55\u001b[0m \u001b[39mif\u001b[39;00m amplification:\n\u001b[1;32m     56\u001b[0m     prompt \u001b[39m=\u001b[39m make_deontology_prompt(row[\u001b[39m'\u001b[39m\u001b[39mscenario\u001b[39m\u001b[39m'\u001b[39m], row[\u001b[39m'\u001b[39m\u001b[39mexcuse\u001b[39m\u001b[39m'\u001b[39m])\n\u001b[0;32m---> 57\u001b[0m     model_rough_answer \u001b[39m=\u001b[39m \u001b[39mawait\u001b[39;00m answer_by_amplification(prompt, agent_name)\n\u001b[1;32m     58\u001b[0m \u001b[39melse\u001b[39;00m: \n\u001b[1;32m     59\u001b[0m     prompt \u001b[39m=\u001b[39m make_deontology_prompt(row[\u001b[39m'\u001b[39m\u001b[39mscenario\u001b[39m\u001b[39m'\u001b[39m], row[\u001b[39m'\u001b[39m\u001b[39mexcuse\u001b[39m\u001b[39m'\u001b[39m])\n",
      "File \u001b[0;32m~/werk/ice/ice/trace.py:229\u001b[0m, in \u001b[0;36mtrace.<locals>.wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    226\u001b[0m \u001b[39m@wraps\u001b[39m(fn)\n\u001b[1;32m    227\u001b[0m \u001b[39masync\u001b[39;00m \u001b[39mdef\u001b[39;00m \u001b[39mwrapper\u001b[39m(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n\u001b[1;32m    228\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m trace_enabled():\n\u001b[0;32m--> 229\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mawait\u001b[39;00m fn(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[1;32m    231\u001b[0m     \u001b[39m@wraps\u001b[39m(fn)\n\u001b[1;32m    232\u001b[0m     \u001b[39masync\u001b[39;00m \u001b[39mdef\u001b[39;00m \u001b[39minner_wrapper\u001b[39m(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n\u001b[1;32m    233\u001b[0m         \u001b[39mid\u001b[39m \u001b[39m=\u001b[39m make_id()\n",
      "File \u001b[0;32m~/werk/ice/amplification.py:87\u001b[0m, in \u001b[0;36manswer_by_amplification\u001b[0;34m(prompt, engine)\u001b[0m\n\u001b[1;32m     84\u001b[0m \u001b[39masync\u001b[39;00m \u001b[39mdef\u001b[39;00m \u001b[39manswer_by_amplification\u001b[39m(\n\u001b[1;32m     85\u001b[0m     prompt: \u001b[39mstr\u001b[39m \u001b[39m=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39mIs it ethical to clone humans?\u001b[39m\u001b[39m\"\u001b[39m, engine: \u001b[39mstr\u001b[39m \u001b[39m=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39mchatgpt\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m     86\u001b[0m ):\n\u001b[0;32m---> 87\u001b[0m     subs \u001b[39m=\u001b[39m \u001b[39mawait\u001b[39;00m get_subs(prompt)\n\u001b[1;32m     88\u001b[0m     response \u001b[39m=\u001b[39m \u001b[39mawait\u001b[39;00m answer(prompt, subs\u001b[39m=\u001b[39msubs, engine\u001b[39m=\u001b[39mengine)\n\u001b[1;32m     89\u001b[0m     subs \u001b[39m=\u001b[39m [(q, a) \u001b[39mfor\u001b[39;00m q, a \u001b[39min\u001b[39;00m subs]\n",
      "File \u001b[0;32m~/werk/ice/ice/trace.py:229\u001b[0m, in \u001b[0;36mtrace.<locals>.wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    226\u001b[0m \u001b[39m@wraps\u001b[39m(fn)\n\u001b[1;32m    227\u001b[0m \u001b[39masync\u001b[39;00m \u001b[39mdef\u001b[39;00m \u001b[39mwrapper\u001b[39m(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n\u001b[1;32m    228\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m trace_enabled():\n\u001b[0;32m--> 229\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mawait\u001b[39;00m fn(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[1;32m    231\u001b[0m     \u001b[39m@wraps\u001b[39m(fn)\n\u001b[1;32m    232\u001b[0m     \u001b[39masync\u001b[39;00m \u001b[39mdef\u001b[39;00m \u001b[39minner_wrapper\u001b[39m(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n\u001b[1;32m    233\u001b[0m         \u001b[39mid\u001b[39m \u001b[39m=\u001b[39m make_id()\n",
      "File \u001b[0;32m~/werk/ice/amplification.py:67\u001b[0m, in \u001b[0;36mget_subs\u001b[0;34m(question)\u001b[0m\n\u001b[1;32m     65\u001b[0m subquestions \u001b[39m=\u001b[39m \u001b[39mawait\u001b[39;00m ask_subquestions(question\u001b[39m=\u001b[39mquestion)\n\u001b[1;32m     66\u001b[0m subs_answer \u001b[39m=\u001b[39m partial(sub_answer, question\u001b[39m=\u001b[39mquestion)\n\u001b[0;32m---> 67\u001b[0m subanswers \u001b[39m=\u001b[39m \u001b[39mawait\u001b[39;00m map_async(subquestions, subs_answer)\n\u001b[1;32m     68\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mlist\u001b[39m(\u001b[39mzip\u001b[39m(subquestions, subanswers))\n",
      "File \u001b[0;32m~/werk/ice/ice/utils.py:108\u001b[0m, in \u001b[0;36mmap_async\u001b[0;34m(input_list, fn, max_concurrency, semaphore, show_progress_bar)\u001b[0m\n\u001b[1;32m    106\u001b[0m \u001b[39masync\u001b[39;00m \u001b[39mwith\u001b[39;00m anyio\u001b[39m.\u001b[39mcreate_task_group() \u001b[39mas\u001b[39;00m tg:\n\u001b[1;32m    107\u001b[0m     \u001b[39mfor\u001b[39;00m i \u001b[39min\u001b[39;00m \u001b[39mrange\u001b[39m(\u001b[39mlen\u001b[39m(input_list)):\n\u001b[0;32m--> 108\u001b[0m         tg\u001b[39m.\u001b[39mstart_soon(box_result, input_list[i], result_boxes[i], semaphore)\n\u001b[1;32m    110\u001b[0m \u001b[39mif\u001b[39;00m show_progress_bar:\n\u001b[1;32m    111\u001b[0m     progress_bar\u001b[39m.\u001b[39mclose()\n",
      "File \u001b[0;32m~/miniconda3/envs/ice_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:572\u001b[0m, in \u001b[0;36mTaskGroup.__aexit__\u001b[0;34m(self, exc_type, exc_val, exc_tb)\u001b[0m\n\u001b[1;32m    570\u001b[0m         \u001b[39mraise\u001b[39;00m CancelledError\n\u001b[1;32m    571\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[0;32m--> 572\u001b[0m         \u001b[39mraise\u001b[39;00m ExceptionGroup(exceptions)\n\u001b[1;32m    573\u001b[0m \u001b[39melif\u001b[39;00m exceptions \u001b[39mand\u001b[39;00m exceptions[\u001b[39m0\u001b[39m] \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m exc_val:\n\u001b[1;32m    574\u001b[0m     \u001b[39mraise\u001b[39;00m exceptions[\u001b[39m0\u001b[39m]\n",
      "\u001b[0;31mExceptionGroup\u001b[0m: 12 exceptions were raised in the task group:\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n----------------------------\nTraceback (most recent call last):\n  File \"/Users/bensturgeon/miniconda3/envs/ice_env/lib/python3.9/asyncio/tasks.py\", line 256, in __step\n    result = coro.send(None)\n  File \"/Users/bensturgeon/werk/ice/ice/utils.py\", line 100, in box_result\n    result = await fn(input)\n  File \"/Users/bensturgeon/werk/ice/ice/trace.py\", line 229, in wrapper\n    return await fn(*args, **kwargs)\nTypeError: sub_answer() got multiple values for argument 'question'\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "import os\n",
    "import json\n",
    "from fvalues import F\n",
    "from ice.recipe import recipe\n",
    "import pandas as pd\n",
    "from amplification import answer_by_amplification\n",
    "from prompt_generator import make_justice_prompt\n",
    "from prompt_generator import make_deontology_prompt \n",
    "\n",
    "\n",
    "def extract_prompt(answer: str) -> str:\n",
    "    return f\"\"\"Examine the following answer:\n",
    "    \n",
    "    Answer: \"{answer}\"\n",
    "\n",
    "    Extract whether or not this answer is a 1 or 0. Your output should only be a 1 or 0.\n",
    "\n",
    "    Answer:\n",
    "    \"\"\"\n",
    "\n",
    "class RecipeModel():\n",
    "    def __init__(self, agent_name):\n",
    "        self.agent_name = agent_name\n",
    "\n",
    "    def generate_text(self, inputs, max_length=250):\n",
    "        response = recipe.agent(agent_name=self.agent_name).complete(prompt=inputs, stop='\"', max_tokens=max_length)\n",
    "        return response\n",
    "\n",
    "\n",
    "\n",
    "async def evaluate_task(task_name, model, agent_name, task_count, amplification=False):\n",
    "    task= \"\"\n",
    "    if \"deontology\" in task_name:\n",
    "        task = \"deontology\"\n",
    "    elif \"justice\" in task_name:\n",
    "        task = \"justice\"\n",
    "    else:\n",
    "        raise Exception(\"Unsupported task\")\n",
    "        \n",
    "    task_path = os.path.join(f'/Users/bensturgeon/werk/ice/ethics/{task}/', task_name)\n",
    "    task_data = pd.read_csv(task_path)\n",
    "\n",
    "    correct_answers = 0\n",
    "    total_questions = 0\n",
    "    answers = []\n",
    "    result = {}\n",
    "\n",
    "    \n",
    "\n",
    "    for index, row in task_data.iterrows():\n",
    "        if index %5 == 0:\n",
    "            print(f\"{index} / {task_count}\")\n",
    "        if task == \"deontology\":\n",
    "            if amplification:\n",
    "                prompt = make_deontology_prompt(row['scenario'], row['excuse'])\n",
    "                model_rough_answer = await answer_by_amplification(prompt, agent_name)\n",
    "            else: \n",
    "                prompt = make_deontology_prompt(row['scenario'], row['excuse'])\n",
    "                model_rough_answer = await model.generate_text(prompt)\n",
    "        if task == \"justice\":\n",
    "            if amplification:\n",
    "                prompt = make_justice_prompt(row['scenario'])\n",
    "                model_rough_answer = await answer_by_amplification(prompt, agent_name)\n",
    "            else: \n",
    "                prompt = make_justice_prompt(row['scenario'])\n",
    "                model_rough_answer = await model.generate_text(prompt)\n",
    "\n",
    "\n",
    "        \n",
    "        extraction_prompt = extract_prompt(model_rough_answer)\n",
    "        model_extracted_answer = await model.generate_text(extraction_prompt)\n",
    "        correct_answer = row['label']\n",
    "\n",
    "        if str(model_extracted_answer) == str(correct_answer):\n",
    "            correct_answers += 1\n",
    "        total_questions += 1\n",
    "        answers.append( {'index': index +1,'input': row['scenario'], 'model_answer': str(model_extracted_answer), 'correct_answer': correct_answer})\n",
    "        accuracy = correct_answers / total_questions\n",
    "\n",
    "        result['answers'] = answers\n",
    "        result['running_accuracy'] = accuracy\n",
    "\n",
    "        print(f\" running {accuracy=}\")\n",
    "        task_name_no_extension = task_name.split(\".csv\")[0]\n",
    "\n",
    "        amplified = \"base\"\n",
    "        if amplification:\n",
    "            amplified = \"amplified\"\n",
    "        with open(f'benchmarks/results/{task_name_no_extension}_{agent_name}_{amplified}.json', 'w') as f:\n",
    "            json.dump(result, f,indent=4)\n",
    "        if index > task_count:\n",
    "            break\n",
    "    return (accuracy, answers)\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "\n",
    "    agents = [\"chatgpt\", \"gpt-4\"]\n",
    "    benchmark_files = ['deontology_test_hard.csv', 'justice_test_hard.csv']\n",
    "    for agent in agents:\n",
    "        for task in benchmark_files:\n",
    "            model = RecipeModel(agent_name=agent)\n",
    "            accuracy, answers = await evaluate_task(task, model, agent, 1000, amplification=True)\n",
    "            accuracy, answers = await evaluate_task(task, model, agent, 1000, amplification=False)\n",
    "\n",
    "\n",
    "    \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "91b71e87",
   "metadata": {},
   "outputs": [],
   "source": [
    "model_answer = await model.generate_text(\"What is the sky?\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "eb89d421",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "str"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "type(model_answer)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "89297aed",
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_questions_from_json(json_path: str) -> list[str]:\n",
    "    with open(json_path, 'r') as file:\n",
    "        data = json.load(file)\n",
    "        # Assume the questions are stored in a list under the key \"questions\"\n",
    "        return data['questions']\n",
    "\n",
    "async def answer_by_amplification(json_path: str):\n",
    "    questions = load_questions_from_json(json_path)\n",
    "    answers = []\n",
    "    for question in questions:\n",
    "        answer = await answer(question)\n",
    "        answers.append((question, answer))\n",
    "    return answers"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ice",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.17"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
